// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ActivityMode.
const (
	AllPvP      ActivityMode = "allPvP"
	Competitive ActivityMode = "competitive"
	IronBanner  ActivityMode = "ironBanner"
	Quickplay   ActivityMode = "quickplay"
)

// Defines values for ConfidenceLevel.
const (
	HighConfidenceLevel     ConfidenceLevel = "high"
	LowConfidenceLevel      ConfidenceLevel = "low"
	MediumConfidenceLevel   ConfidenceLevel = "medium"
	NoMatchConfidenceLevel  ConfidenceLevel = "noMatch"
	NotFoundConfidenceLevel ConfidenceLevel = "notFound"
)

// Defines values for ConfidenceSource.
const (
	SystemConfidenceSource ConfidenceSource = "system"
	UserConfidenceSource   ConfidenceSource = "user"
)

// Defines values for InternalError.
const (
	ErrDestinyServerDown  InternalError = "DestinyServerDown"
	ErrInternalSystemDown InternalError = "InternalSystemDown"
	ErrUnknownError       InternalError = "UnknownError"
)

// ActivityHistory defines model for ActivityHistory.
type ActivityHistory struct {
	Activity string `firestore:"activity" json:"activity"`

	// ActivityHash Hash id of the type of activity: Strike, Competitive, QuickPlay, etc.
	ActivityHash int64 `firestore:"activityHash" json:"activityHash"`

	// ActivityIcon URL to the icon for the type of activity, IB, Crucible, etc.
	ActivityIcon string `firestore:"activityIcon" json:"activityIcon"`
	Description  string `firestore:"description" json:"description"`

	// ImageURL URL for the image of the destination activity
	ImageURL string `firestore:"imageUrl" json:"imageUrl"`

	// InstanceID Id to get more details about the particular game
	InstanceID string `firestore:"instanceId" json:"instanceId"`
	IsPrivate  *bool  `firestore:"isPrivate" json:"isPrivate,omitempty"`
	Location   string `firestore:"location" json:"location"`

	// Mode Name
	Mode   *string   `firestore:"mode" json:"mode,omitempty"`
	Period time.Time `firestore:"period" json:"period"`

	// PersonalValues All Player Stats from a match that we currently care about
	PersonalValues *PlayerStats `firestore:"playerStats,omitempty" json:"personalValues,omitempty"`
	ReferenceID    int64        `firestore:"referenceId" json:"referenceId"`
}

// ActivityMode defines model for ActivityMode.
type ActivityMode string

// Aggregate defines model for Aggregate.
type Aggregate struct {
	ActivityDetails ActivityHistory                `firestore:"activityHistory" json:"activityDetails"`
	ActivityID      string                         `firestore:"activityId" json:"activityId"`
	CreatedAt       time.Time                      `firestore:"createdAt" json:"createdAt"`
	ID              string                         `firestore:"id" json:"id"`
	Performance     map[string]InstancePerformance `firestore:"performance" json:"performance"`
	SnapshotLinks   map[string]SnapshotLink        `firestore:"snapshotLinks" json:"snapshotLinks"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken Access token value.
	AccessToken string `json:"accessToken"`

	// ExpiresIn The time duration in which the access token will be expired.
	ExpiresIn int    `json:"expiresIn"`
	Id        string `json:"id"`

	// MembershipId Membership identification value.
	MembershipId string `json:"membershipId"`

	// PrimaryMembershipId Membership that is mainly used
	PrimaryMembershipId string `json:"primaryMembershipId"`

	// RefreshExpiresIn The time duration in which the refresh token will be expired.
	RefreshExpiresIn int `json:"refreshExpiresIn"`

	// RefreshToken Refresh token for acquiring new access token after it is expired.
	RefreshToken string    `json:"refreshToken"`
	Timestamp    time.Time `json:"timestamp"`

	// TokenType Type of the access token.
	TokenType string `json:"tokenType"`
}

// BaseItemInfo defines model for BaseItemInfo.
type BaseItemInfo struct {
	BucketHash int64       `firestore:"bucketHash" json:"bucketHash"`
	Damage     *DamageInfo `firestore:"damageInfo" json:"damage,omitempty"`
	InstanceId string      `firestore:"instanceId" json:"instanceId"`
	ItemHash   int64       `firestore:"itemHash" json:"itemHash"`
	Name       string      `firestore:"name" json:"name"`
}

// Character defines model for Character.
type Character struct {
	Class               string `firestore:"class" json:"class"`
	CurrentTitle        string `firestore:"currentTitle" json:"currentTitle"`
	EmblemBackgroundURL string `firestore:"emblemBackgroundURL" json:"emblemBackgroundURL"`
	EmblemURL           string `firestore:"emblemURL" json:"emblemURL"`
	Id                  string `firestore:"id" json:"id"`
	Light               int64  `firestore:"light" json:"light"`
	Race                string `firestore:"race" json:"race"`
}

// CharacterSnapshot defines model for CharacterSnapshot.
type CharacterSnapshot struct {
	// CharacterID Id of the character being recorded
	CharacterID string `firestore:"characterId" json:"characterId"`

	// Hash Hash of all the items to give us a unique key
	Hash string `firestore:"hash" json:"hash"`

	// ID Id of the snapshot
	ID string `firestore:"id" json:"id"`

	// IsOriginal Will be default false for almost all Snapshots. Will only be set for the first snapshot entry with the selected items.
	IsOriginal bool `firestore:"isOriginal" json:"isOriginal"`

	// Loadout All buckets that we currently care about, Kinetic, Energy, Heavy and Class for now. Each will be a key in the items.
	Loadout Loadout `firestore:"loadout" json:"loadout"`

	// Name Name of the snapshot, will probably be generated by default by the system but can be changed by a user
	Name string `firestore:"name" json:"name"`

	// ParentID Optional ID that will link to the first ever snapshot
	// that has the same hash. If the parent ID is provided
	// then the snapshot data will be empty. Search by the hash
	// to find the original data.
	ParentID *string `firestore:"parentId" json:"parentId,omitempty"`

	// Timestamp Timestamp for when the snapshot was taken
	Timestamp time.Time `firestore:"timestamp" json:"timestamp"`

	// UserID Id of the user it belongs to
	UserID string `firestore:"userId" json:"userId"`
}

// Color defines model for Color.
type Color struct {
	Alpha int `firestore:"alpha" json:"alpha"`
	Blue  int `firestore:"blue" json:"blue"`
	Green int `firestore:"green" json:"green"`
	Red   int `firestore:"red" json:"red"`
}

// ConfidenceLevel defines model for ConfidenceLevel.
type ConfidenceLevel string

// ConfidenceSource defines model for ConfidenceSource.
type ConfidenceSource string

// DamageInfo defines model for DamageInfo.
type DamageInfo struct {
	Color           Color  `firestore:"color" json:"color"`
	DamageIcon      string `firestore:"damageIcon" json:"damageIcon"`
	DamageType      string `firestore:"damageType" json:"damageType"`
	TransparentIcon string `firestore:"transparentIcon" json:"transparentIcon"`
}

// DetailActivity defines model for DetailActivity.
type DetailActivity struct {
	Activity  ActivityHistory `firestore:"activityHistory" json:"activity"`
	Aggregate *Aggregate      `json:"aggregate,omitempty"`
}

// GunStat defines model for GunStat.
type GunStat struct {
	Description string `firestore:"description" json:"description"`

	// Hash The hash ID of the stat.
	Hash int64  `firestore:"hash" json:"hash"`
	Name string `firestore:"name" json:"name"`

	// Value The value of the stat.
	Value int64 `firestore:"value" json:"value"`
}

// InstancePerformance defines model for InstancePerformance.
type InstancePerformance struct {
	Extra *map[string]UniqueStatValue `firestore:"extra" json:"extra,omitempty"`

	// PlayerStats All Player Stats from a match that we currently care about
	PlayerStats PlayerStats             `firestore:"playerStats,omitempty" json:"playerStats"`
	Weapons     []WeaponInstanceMetrics `firestore:"weapons" json:"weapons"`
}

// InternalError defines model for InternalError.
type InternalError string

// ItemProperties The response object for retrieving an individual instanced item. None of these components are relevant for an item that doesn't have an "itemInstanceId": for those, get your information from the DestinyInventoryDefinition.
type ItemProperties struct {
	BaseInfo BaseItemInfo `firestore:"baseItemInfo" json:"baseInfo"`

	// CharacterId If the item is on a character, this will return the ID of the character that is holding the item.
	CharacterId *string `firestore:"characterId" json:"characterId"`

	// Perks Information specifically about the perks currently active on the item. COMPONENT TYPE: ItemPerks
	Perks []Perk `firestore:"perks" json:"perks"`

	// Sockets Information about the sockets of the item: which are currently active, what potential sockets you could have and the stats/abilities/perks you can gain from them. COMPONENT TYPE: ItemSockets
	Sockets *[]Socket `firestore:"sockets" json:"sockets,omitempty"`

	// Stats Information about the computed stats of the item: power, defense, etc... COMPONENT TYPE: ItemStats
	Stats Stats `firestore:"stats" json:"stats"`
}

// ItemSnapshot defines model for ItemSnapshot.
type ItemSnapshot struct {
	// BucketHash Hash of which bucket this item can be equipped in
	BucketHash *int64 `firestore:"bucketHash" json:"bucketHash,omitempty"`

	// ItemProperties The response object for retrieving an individual instanced item. None of these components are relevant for an item that doesn't have an "itemInstanceId": for those, get your information from the DestinyInventoryDefinition.
	ItemProperties ItemProperties `firestore:"itemProperties" json:"details"`

	// InstanceID Specific instance id for the item
	InstanceID string `firestore:"instanceId" json:"instanceId"`

	// ItemHash Id used to find the definition of the item
	ItemHash int64 `firestore:"itemHash" json:"itemHash"`

	// Name Name of the particular item
	Name string `firestore:"name" json:"name"`
}

// Loadout All buckets that we currently care about, Kinetic, Energy, Heavy and Class for now. Each will be a key in the items.
type Loadout map[string]ItemSnapshot

// Perk defines model for Perk.
type Perk struct {
	Description *string `firestore:"description" json:"description,omitempty"`

	// Hash The hash ID of the perk
	Hash int64 `firestore:"hash" json:"hash"`

	// IconPath link to icon
	IconPath *string `firestore:"iconPath" json:"iconPath,omitempty"`
	Name     string  `firestore:"name" json:"name"`
}

// PlayerStats All Player Stats from a match that we currently care about
type PlayerStats struct {
	Assists    *StatsValuePair `firestore:"statsValuePair" json:"assists,omitempty"`
	Deaths     *StatsValuePair `firestore:"statsValuePair" json:"deaths,omitempty"`
	FireTeamId *StatsValuePair `firestore:"statsValuePair" json:"fireTeamId,omitempty"`
	Kd         *StatsValuePair `firestore:"statsValuePair" json:"kd,omitempty"`
	Kda        *StatsValuePair `firestore:"statsValuePair" json:"kda,omitempty"`
	Kills      *StatsValuePair `firestore:"statsValuePair" json:"kills,omitempty"`
	Standing   *StatsValuePair `firestore:"statsValuePair" json:"standing,omitempty"`
	Team       *StatsValuePair `firestore:"statsValuePair" json:"team,omitempty"`
	TimePlayed *StatsValuePair `firestore:"statsValuePair" json:"timePlayed,omitempty"`
}

// Pong defines model for Pong.
type Pong struct {
	Ping string `json:"ping"`
}

// Profile defines model for Profile.
type Profile struct {
	Characters   []Character `json:"characters"`
	DisplayName  string      `json:"displayName"`
	Id           string      `json:"id"`
	MembershipId string      `json:"membershipId"`
	UniqueName   string      `json:"uniqueName"`
}

// Session defines model for Session.
type Session struct {
	CharacterID        string     `firestore:"characterId" json:"characterId"`
	CompletedAt        *time.Time `firestore:"completedAt" json:"completedAt,omitempty"`
	ID                 string     `firestore:"id" json:"id"`
	LastSeenActivityID *string    `firestore:"lastSeenActivityId" json:"lastSeenActivityId,omitempty"`
	LastSeenTimestamp  *time.Time `firestore:"lastSeenTimestamp" json:"lastSeenTimestamp,omitempty"`
	Name               *string    `firestore:"name" json:"name,omitempty"`
	StartedAt          time.Time  `firestore:"startedAt" json:"startedAt"`
	UserID             string     `firestore:"userId" json:"userId"`
}

// SnapshotLink defines model for SnapshotLink.
type SnapshotLink struct {
	CharacterID      string           `firestore:"characterId" json:"characterId"`
	ConfidenceLevel  ConfidenceLevel  `firestore:"confidenceLevel" json:"confidenceLevel"`
	ConfidenceSource ConfidenceSource `firestore:"confidenceSource" json:"confidenceSource"`
	CreatedAt        time.Time        `firestore:"createdAt" json:"createdAt"`
	SnapshotID       *string          `firestore:"snapshotId" json:"snapshotId,omitempty"`
}

// Socket defines model for Socket.
type Socket struct {
	Description string  `firestore:"description" json:"description"`
	Icon        *string `firestore:"icon" json:"icon,omitempty"`

	// IsEnabled Whether the socket plug is enabled or not.
	IsEnabled *bool `firestore:"isEnabled" json:"isEnabled,omitempty"`

	// IsVisible Whether the socket plug is visible or not.
	IsVisible *bool  `firestore:"isVisible" json:"isVisible,omitempty"`
	Name      string `firestore:"name" json:"name"`

	// PlugHash The hash ID of the socket plug.
	PlugHash int `firestore:"plugHash" json:"plugHash"`
}

// Stats defines model for Stats.
type Stats map[string]GunStat

// StatsValuePair defines model for StatsValuePair.
type StatsValuePair struct {
	// DisplayValue Localized formatted version of the value.
	DisplayValue *string `firestore:"displayValue" json:"displayValue,omitempty"`

	// Value Raw value of the statistic
	Value *float64 `firestore:"value" json:"value,omitempty"`
}

// Team defines model for Team.
type Team struct {
	ID       string  `json:"id"`
	Score    string  `json:"score"`
	Standing string  `json:"standing"`
	TeamName *string `json:"teamName,omitempty"`
}

// UniqueStatValue defines model for UniqueStatValue.
type UniqueStatValue struct {
	// ActivityID When a stat represents the best, most, longest, fastest or some other personal best, the actual activity ID where that personal best was established is available on this property.
	ActivityID *int64 `firestore:"activityId" json:"activityId"`

	// Basic Basic stat value.
	Basic StatsValuePair `firestore:"basic" json:"basic"`
	Name  *string        `firestore:"name" json:"name,omitempty"`

	// Pga Per game average for the statistic, if applicable
	Pga *StatsValuePair `firestore:"pga" json:"pga,omitempty"`

	// Weighted Weighted value of the stat if a weight greater than 1 has been assigned.
	Weighted *StatsValuePair `firestore:"weighted" json:"weighted,omitempty"`
}

// WeaponInstanceMetrics defines model for WeaponInstanceMetrics.
type WeaponInstanceMetrics struct {
	// ItemProperties The response object for retrieving an individual instanced item. None of these components are relevant for an item that doesn't have an "itemInstanceId": for those, get your information from the DestinyInventoryDefinition.
	ItemProperties *ItemProperties `firestore:"itemProperties" json:"properties,omitempty"`

	// ReferenceID The hash ID of the item definition that describes the weapon.
	ReferenceID *int64                      `firestore:"referenceId" json:"referenceId,omitempty"`
	Stats       *map[string]UniqueStatValue `firestore:"stats" json:"stats,omitempty"`
}

// XMembershipID defines model for X-Membership-ID.
type XMembershipID = string

// XUserID defines model for X-User-ID.
type XUserID = string

// SessionCheckInJSONBody defines parameters for SessionCheckIn.
type SessionCheckInJSONBody struct {
	SessionID string `json:"sessionId"`
}

// SessionCheckInParams defines parameters for SessionCheckIn.
type SessionCheckInParams struct {
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// GetActivitiesParams defines parameters for GetActivities.
type GetActivitiesParams struct {
	Count         int64         `form:"count" json:"count"`
	Page          int64         `form:"page" json:"page"`
	CharacterID   string        `form:"characterId" json:"characterId"`
	Mode          *ActivityMode `form:"mode,omitempty" json:"mode,omitempty"`
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// GetActivityParams defines parameters for GetActivity.
type GetActivityParams struct {
	CharacterID   string        `form:"characterId" json:"characterId"`
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Code string `json:"code"`
}

// ProfileParams defines parameters for Profile.
type ProfileParams struct {
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// RefreshTokenJSONBody defines parameters for RefreshToken.
type RefreshTokenJSONBody struct {
	Code string `json:"code"`
}

// GetSessionsParams defines parameters for GetSessions.
type GetSessionsParams struct {
	Count         int64         `form:"count" json:"count"`
	Page          int64         `form:"page" json:"page"`
	CharacterID   string        `form:"characterId" json:"characterId"`
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// StartSessionJSONBody defines parameters for StartSession.
type StartSessionJSONBody struct {
	CharacterID string `json:"characterId"`
}

// StartSessionParams defines parameters for StartSession.
type StartSessionParams struct {
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// UpdateSessionJSONBody defines parameters for UpdateSession.
type UpdateSessionJSONBody struct {
	CharacterID string  `json:"characterId"`
	CompletedAt *string `json:"completedAt,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateSessionParams defines parameters for UpdateSession.
type UpdateSessionParams struct {
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// GetSessionAggregatesParams defines parameters for GetSessionAggregates.
type GetSessionAggregatesParams struct {
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// GetSnapshotsParams defines parameters for GetSnapshots.
type GetSnapshotsParams struct {
	Count       int64   `form:"count" json:"count"`
	Page        int64   `form:"page" json:"page"`
	CharacterID string  `form:"characterId" json:"characterId"`
	XUserID     XUserID `json:"X-User-ID"`
}

// CreateSnapshotJSONBody defines parameters for CreateSnapshot.
type CreateSnapshotJSONBody struct {
	CharacterID string `json:"characterId"`
}

// CreateSnapshotParams defines parameters for CreateSnapshot.
type CreateSnapshotParams struct {
	XUserID       XUserID       `json:"X-User-ID"`
	XMembershipID XMembershipID `json:"X-Membership-ID"`
}

// GetSnapshotParams defines parameters for GetSnapshot.
type GetSnapshotParams struct {
	CharacterID string  `form:"characterId" json:"characterId"`
	XUserID     XUserID `json:"X-User-ID"`
}

// SessionCheckInJSONRequestBody defines body for SessionCheckIn for application/json ContentType.
type SessionCheckInJSONRequestBody SessionCheckInJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody RefreshTokenJSONBody

// StartSessionJSONRequestBody defines body for StartSession for application/json ContentType.
type StartSessionJSONRequestBody StartSessionJSONBody

// UpdateSessionJSONRequestBody defines body for UpdateSession for application/json ContentType.
type UpdateSessionJSONRequestBody UpdateSessionJSONBody

// CreateSnapshotJSONRequestBody defines body for CreateSnapshot for application/json ContentType.
type CreateSnapshotJSONRequestBody CreateSnapshotJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /actions/session-checkin)
	SessionCheckIn(c *gin.Context, params SessionCheckInParams)

	// (GET /activities)
	GetActivities(c *gin.Context, params GetActivitiesParams)

	// (GET /activities/{activityId})
	GetActivity(c *gin.Context, activityID string, params GetActivityParams)

	// (POST /login)
	Login(c *gin.Context)

	// (GET /ping)
	GetPing(c *gin.Context)

	// (GET /profile)
	Profile(c *gin.Context, params ProfileParams)

	// (POST /refresh)
	RefreshToken(c *gin.Context)

	// (GET /sessions)
	GetSessions(c *gin.Context, params GetSessionsParams)

	// (POST /sessions)
	StartSession(c *gin.Context, params StartSessionParams)

	// (PUT /sessions/{sessionId})
	UpdateSession(c *gin.Context, sessionId string, params UpdateSessionParams)

	// (GET /sessions/{sessionId}/aggregates)
	GetSessionAggregates(c *gin.Context, sessionId string, params GetSessionAggregatesParams)

	// (GET /snapshots)
	GetSnapshots(c *gin.Context, params GetSnapshotsParams)

	// (POST /snapshots)
	CreateSnapshot(c *gin.Context, params CreateSnapshotParams)

	// (GET /snapshots/{snapshotId})
	GetSnapshot(c *gin.Context, snapshotID string, params GetSnapshotParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SessionCheckIn operation middleware
func (siw *ServerInterfaceWrapper) SessionCheckIn(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SessionCheckInParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SessionCheckIn(c, params)
}

// GetActivities operation middleware
func (siw *ServerInterfaceWrapper) GetActivities(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivitiesParams

	// ------------- Required query parameter "count" -------------

	if paramValue := c.Query("count"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument count is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "count", c.Request.URL.Query(), &params.Count)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter count: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument page is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "characterId" -------------

	if paramValue := c.Query("characterId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument characterId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "characterId", c.Request.URL.Query(), &params.CharacterID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter characterId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "mode" -------------

	err = runtime.BindQueryParameter("form", true, false, "mode", c.Request.URL.Query(), &params.Mode)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter mode: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivities(c, params)
}

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(c *gin.Context) {

	var err error

	// ------------- Path parameter "activityId" -------------
	var activityID string

	err = runtime.BindStyledParameterWithOptions("simple", "activityId", c.Param("activityId"), &activityID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter activityId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivityParams

	// ------------- Required query parameter "characterId" -------------

	if paramValue := c.Query("characterId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument characterId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "characterId", c.Request.URL.Query(), &params.CharacterID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter characterId: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivity(c, activityID, params)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPing(c)
}

// Profile operation middleware
func (siw *ServerInterfaceWrapper) Profile(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ProfileParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Profile(c, params)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// GetSessions operation middleware
func (siw *ServerInterfaceWrapper) GetSessions(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSessionsParams

	// ------------- Required query parameter "count" -------------

	if paramValue := c.Query("count"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument count is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "count", c.Request.URL.Query(), &params.Count)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter count: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument page is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "characterId" -------------

	if paramValue := c.Query("characterId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument characterId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "characterId", c.Request.URL.Query(), &params.CharacterID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter characterId: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSessions(c, params)
}

// StartSession operation middleware
func (siw *ServerInterfaceWrapper) StartSession(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StartSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartSession(c, params)
}

// UpdateSession operation middleware
func (siw *ServerInterfaceWrapper) UpdateSession(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", c.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateSessionParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateSession(c, sessionId, params)
}

// GetSessionAggregates operation middleware
func (siw *ServerInterfaceWrapper) GetSessionAggregates(c *gin.Context) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId string

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", c.Param("sessionId"), &sessionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sessionId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSessionAggregatesParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSessionAggregates(c, sessionId, params)
}

// GetSnapshots operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshots(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotsParams

	// ------------- Required query parameter "count" -------------

	if paramValue := c.Query("count"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument count is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "count", c.Request.URL.Query(), &params.Count)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter count: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument page is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "characterId" -------------

	if paramValue := c.Query("characterId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument characterId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "characterId", c.Request.URL.Query(), &params.CharacterID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter characterId: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSnapshots(c, params)
}

// CreateSnapshot operation middleware
func (siw *ServerInterfaceWrapper) CreateSnapshot(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSnapshotParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	// ------------- Required header parameter "X-Membership-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Membership-ID")]; found {
		var XMembershipID XMembershipID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Membership-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Membership-ID", valueList[0], &XMembershipID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Membership-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XMembershipID = XMembershipID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Membership-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSnapshot(c, params)
}

// GetSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetSnapshot(c *gin.Context) {

	var err error

	// ------------- Path parameter "snapshotId" -------------
	var snapshotID string

	err = runtime.BindStyledParameterWithOptions("simple", "snapshotId", c.Param("snapshotId"), &snapshotID, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter snapshotId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSnapshotParams

	// ------------- Required query parameter "characterId" -------------

	if paramValue := c.Query("characterId"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument characterId is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "characterId", c.Request.URL.Query(), &params.CharacterID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter characterId: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-User-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-User-ID")]; found {
		var XUserID XUserID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-User-ID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-User-ID", valueList[0], &XUserID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-User-ID: %w", err), http.StatusBadRequest)
			return
		}

		params.XUserID = XUserID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-User-ID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSnapshot(c, snapshotID, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/actions/session-checkin", wrapper.SessionCheckIn)
	router.GET(options.BaseURL+"/activities", wrapper.GetActivities)
	router.GET(options.BaseURL+"/activities/:activityId", wrapper.GetActivity)
	router.POST(options.BaseURL+"/login", wrapper.Login)
	router.GET(options.BaseURL+"/ping", wrapper.GetPing)
	router.GET(options.BaseURL+"/profile", wrapper.Profile)
	router.POST(options.BaseURL+"/refresh", wrapper.RefreshToken)
	router.GET(options.BaseURL+"/sessions", wrapper.GetSessions)
	router.POST(options.BaseURL+"/sessions", wrapper.StartSession)
	router.PUT(options.BaseURL+"/sessions/:sessionId", wrapper.UpdateSession)
	router.GET(options.BaseURL+"/sessions/:sessionId/aggregates", wrapper.GetSessionAggregates)
	router.GET(options.BaseURL+"/snapshots", wrapper.GetSnapshots)
	router.POST(options.BaseURL+"/snapshots", wrapper.CreateSnapshot)
	router.GET(options.BaseURL+"/snapshots/:snapshotId", wrapper.GetSnapshot)
}

type SessionCheckInRequestObject struct {
	Params SessionCheckInParams
	Body   *SessionCheckInJSONRequestBody
}

type SessionCheckInResponseObject interface {
	VisitSessionCheckInResponse(w http.ResponseWriter) error
}

type SessionCheckIn200JSONResponse bool

func (response SessionCheckIn200JSONResponse) VisitSessionCheckInResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetActivitiesRequestObject struct {
	Params GetActivitiesParams
}

type GetActivitiesResponseObject interface {
	VisitGetActivitiesResponse(w http.ResponseWriter) error
}

type GetActivities200JSONResponse []DetailActivity

func (response GetActivities200JSONResponse) VisitGetActivitiesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetActivityRequestObject struct {
	ActivityID string `json:"activityId"`
	Params     GetActivityParams
}

type GetActivityResponseObject interface {
	VisitGetActivityResponse(w http.ResponseWriter) error
}

type GetActivity200JSONResponse struct {
	Activity  ActivityHistory `firestore:"activityHistory" json:"activity"`
	Aggregate *Aggregate      `json:"aggregate,omitempty"`
	Teams     []Team          `json:"teams"`
}

func (response GetActivity200JSONResponse) VisitGetActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse Pong

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ProfileRequestObject struct {
	Params ProfileParams
}

type ProfileResponseObject interface {
	VisitProfileResponse(w http.ResponseWriter) error
}

type Profile200JSONResponse Profile

func (response Profile200JSONResponse) VisitProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Profile503JSONResponse struct {
	// Message User friendly description of the error
	Message string        `json:"message"`
	Status  InternalError `json:"status"`
}

func (response Profile503JSONResponse) VisitProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse AuthResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionsRequestObject struct {
	Params GetSessionsParams
}

type GetSessionsResponseObject interface {
	VisitGetSessionsResponse(w http.ResponseWriter) error
}

type GetSessions200JSONResponse []Session

func (response GetSessions200JSONResponse) VisitGetSessionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StartSessionRequestObject struct {
	Params StartSessionParams
	Body   *StartSessionJSONRequestBody
}

type StartSessionResponseObject interface {
	VisitStartSessionResponse(w http.ResponseWriter) error
}

type StartSession201JSONResponse Session

func (response StartSession201JSONResponse) VisitStartSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UpdateSessionRequestObject struct {
	SessionId string `json:"sessionId"`
	Params    UpdateSessionParams
	Body      *UpdateSessionJSONRequestBody
}

type UpdateSessionResponseObject interface {
	VisitUpdateSessionResponse(w http.ResponseWriter) error
}

type UpdateSession201JSONResponse Session

func (response UpdateSession201JSONResponse) VisitUpdateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetSessionAggregatesRequestObject struct {
	SessionId string `json:"sessionId"`
	Params    GetSessionAggregatesParams
}

type GetSessionAggregatesResponseObject interface {
	VisitGetSessionAggregatesResponse(w http.ResponseWriter) error
}

type GetSessionAggregates200JSONResponse []Aggregate

func (response GetSessionAggregates200JSONResponse) VisitGetSessionAggregatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSnapshotsRequestObject struct {
	Params GetSnapshotsParams
}

type GetSnapshotsResponseObject interface {
	VisitGetSnapshotsResponse(w http.ResponseWriter) error
}

type GetSnapshots200JSONResponse []CharacterSnapshot

func (response GetSnapshots200JSONResponse) VisitGetSnapshotsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateSnapshotRequestObject struct {
	Params CreateSnapshotParams
	Body   *CreateSnapshotJSONRequestBody
}

type CreateSnapshotResponseObject interface {
	VisitCreateSnapshotResponse(w http.ResponseWriter) error
}

type CreateSnapshot201JSONResponse CharacterSnapshot

func (response CreateSnapshot201JSONResponse) VisitCreateSnapshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type GetSnapshotRequestObject struct {
	SnapshotID string `json:"snapshotId"`
	Params     GetSnapshotParams
}

type GetSnapshotResponseObject interface {
	VisitGetSnapshotResponse(w http.ResponseWriter) error
}

type GetSnapshot200JSONResponse CharacterSnapshot

func (response GetSnapshot200JSONResponse) VisitGetSnapshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /actions/session-checkin)
	SessionCheckIn(ctx context.Context, request SessionCheckInRequestObject) (SessionCheckInResponseObject, error)

	// (GET /activities)
	GetActivities(ctx context.Context, request GetActivitiesRequestObject) (GetActivitiesResponseObject, error)

	// (GET /activities/{activityId})
	GetActivity(ctx context.Context, request GetActivityRequestObject) (GetActivityResponseObject, error)

	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)

	// (GET /profile)
	Profile(ctx context.Context, request ProfileRequestObject) (ProfileResponseObject, error)

	// (POST /refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)

	// (GET /sessions)
	GetSessions(ctx context.Context, request GetSessionsRequestObject) (GetSessionsResponseObject, error)

	// (POST /sessions)
	StartSession(ctx context.Context, request StartSessionRequestObject) (StartSessionResponseObject, error)

	// (PUT /sessions/{sessionId})
	UpdateSession(ctx context.Context, request UpdateSessionRequestObject) (UpdateSessionResponseObject, error)

	// (GET /sessions/{sessionId}/aggregates)
	GetSessionAggregates(ctx context.Context, request GetSessionAggregatesRequestObject) (GetSessionAggregatesResponseObject, error)

	// (GET /snapshots)
	GetSnapshots(ctx context.Context, request GetSnapshotsRequestObject) (GetSnapshotsResponseObject, error)

	// (POST /snapshots)
	CreateSnapshot(ctx context.Context, request CreateSnapshotRequestObject) (CreateSnapshotResponseObject, error)

	// (GET /snapshots/{snapshotId})
	GetSnapshot(ctx context.Context, request GetSnapshotRequestObject) (GetSnapshotResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// SessionCheckIn operation middleware
func (sh *strictHandler) SessionCheckIn(ctx *gin.Context, params SessionCheckInParams) {
	var request SessionCheckInRequestObject

	request.Params = params

	var body SessionCheckInJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SessionCheckIn(ctx, request.(SessionCheckInRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionCheckIn")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SessionCheckInResponseObject); ok {
		if err := validResponse.VisitSessionCheckInResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActivities operation middleware
func (sh *strictHandler) GetActivities(ctx *gin.Context, params GetActivitiesParams) {
	var request GetActivitiesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetActivities(ctx, request.(GetActivitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActivities")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetActivitiesResponseObject); ok {
		if err := validResponse.VisitGetActivitiesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetActivity operation middleware
func (sh *strictHandler) GetActivity(ctx *gin.Context, activityID string, params GetActivityParams) {
	var request GetActivityRequestObject

	request.ActivityID = activityID
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetActivity(ctx, request.(GetActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetActivity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetActivityResponseObject); ok {
		if err := validResponse.VisitGetActivityResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(ctx *gin.Context) {
	var request GetPingRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx, request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		if err := validResponse.VisitGetPingResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Profile operation middleware
func (sh *strictHandler) Profile(ctx *gin.Context, params ProfileParams) {
	var request ProfileRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Profile(ctx, request.(ProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Profile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ProfileResponseObject); ok {
		if err := validResponse.VisitProfileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessions operation middleware
func (sh *strictHandler) GetSessions(ctx *gin.Context, params GetSessionsParams) {
	var request GetSessionsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessions(ctx, request.(GetSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSessionsResponseObject); ok {
		if err := validResponse.VisitGetSessionsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartSession operation middleware
func (sh *strictHandler) StartSession(ctx *gin.Context, params StartSessionParams) {
	var request StartSessionRequestObject

	request.Params = params

	var body StartSessionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartSession(ctx, request.(StartSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StartSessionResponseObject); ok {
		if err := validResponse.VisitStartSessionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateSession operation middleware
func (sh *strictHandler) UpdateSession(ctx *gin.Context, sessionId string, params UpdateSessionParams) {
	var request UpdateSessionRequestObject

	request.SessionId = sessionId
	request.Params = params

	var body UpdateSessionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSession(ctx, request.(UpdateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateSessionResponseObject); ok {
		if err := validResponse.VisitUpdateSessionResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSessionAggregates operation middleware
func (sh *strictHandler) GetSessionAggregates(ctx *gin.Context, sessionId string, params GetSessionAggregatesParams) {
	var request GetSessionAggregatesRequestObject

	request.SessionId = sessionId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSessionAggregates(ctx, request.(GetSessionAggregatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSessionAggregates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSessionAggregatesResponseObject); ok {
		if err := validResponse.VisitGetSessionAggregatesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSnapshots operation middleware
func (sh *strictHandler) GetSnapshots(ctx *gin.Context, params GetSnapshotsParams) {
	var request GetSnapshotsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshots(ctx, request.(GetSnapshotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSnapshotsResponseObject); ok {
		if err := validResponse.VisitGetSnapshotsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSnapshot operation middleware
func (sh *strictHandler) CreateSnapshot(ctx *gin.Context, params CreateSnapshotParams) {
	var request CreateSnapshotRequestObject

	request.Params = params

	var body CreateSnapshotJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSnapshot(ctx, request.(CreateSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateSnapshotResponseObject); ok {
		if err := validResponse.VisitCreateSnapshotResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSnapshot operation middleware
func (sh *strictHandler) GetSnapshot(ctx *gin.Context, snapshotID string, params GetSnapshotParams) {
	var request GetSnapshotRequestObject

	request.SnapshotID = snapshotID
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSnapshot(ctx, request.(GetSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSnapshot")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetSnapshotResponseObject); ok {
		if err := validResponse.VisitGetSnapshotResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x8W3PbOpLwX0Hx+6r2hbZz5uxuTfnNsT0T7zqJJ3ZOZuskDxDZojAiAR4AlKJN+b9v",
	"oQGQ4EUXinJy5vKSikWg0d1o9B34FiWiKAUHrlV0+S0qqaQFaJD411/P3kIxA6kWrDy7uzE/MR5dRgug",
	"KcgojjgtILrsjYsjCb9VTEIaXWpZQRypZAEFNQD0pjRTlJaMZ9Hzcxz99eyjArkbvh8xBvKz/4i0XCWa",
	"rZjevGFKC7lBYqUoQWoGOIC6AX1QcfT1TNCSnSUihQz4GXzVkp5pmuHEOZNgYJoZNRCzuv/jDVULMzAF",
	"lUhWaiYMkeZXwlIi5kQvgJglzf/9pEvyqCVbQkyuRVGCZpqtICZ/qViyfMjpJiagk3MSxdFcyILq6DJi",
	"XP/nv0exx55xDRmycTT6iHFIwl1icO6S8PHDPdEC0WeJ4GQu5CAtMbl7HZNrWSVsloPFvMHzeC4jVgbN",
	"FloTti+EY+CygmbwUebDpHtycZTfxxSUZpyaYTX9g7Rm4syJt13lw/0YTGvMEE2uNOUJ3KV9RO9Ss0UZ",
	"aFIIadDTlOWK0JmoNCJcUqlZUuVUkszgswdXv9TNKGwbBBFf9SDZimoINmsmRA6Uj4JagzFAc5HQyQJQ",
	"AzEQC5FCn6HvtjHpwCUQqgFfgmQCd6w+wSnVcKbZtAUcXLeEEpzmv9C8slru/0uYR5fR/7to9P6F05IX",
	"Rq2AfNRUq+jZaNo5SKjF6hA108hJM3mUoIRrogZv1P2vrY8d7do6A4EstFVDMykKznZHy9Ub86UmUcz+",
	"Bok+SpE6a2NI8RborRMr4FVhyEoa/R7F0W9GwZc5NSjSPH9YPRhcpeCvKecgA6wCyTCgzlZUGuYrA/O6",
	"BfMvAcwrD/MugGmwyzIJmTuTw5bxxuqOfWLUtbShGUmHT2cjN/XIm6MMghX7RALVkF7p0x+uBjQqsr30",
	"jNST9bFFrHmCu0HTlBn5pflDa192bcKdOw4PAajnCQIdooSeFaelWgh9z/hSHYvkYwBkEnZtbHqKg4X6",
	"oqU8vEh3CWrvQShRPa1gzk6lFx9AlYKrweOTgFJPYgkDLtQVfiTafCUro6b7ntFzHMHX0pB7NwDhyThc",
	"rACSVtK6HYyT9YIlCzTvNFxgzfKczIBYcOl5X4tvEWpjDWsXf8jNaAIAwlLgms2ZVcE7iColK6jcvD0U",
	"sF5QTZgiBWU835BKQToEVsJcglrcHs0yB2AMz9yULZv8oQXQuI00MdLJeEY4rNt7ROcaJGFIaX/NhkxD",
	"gNK0KA9UcmaKWeAJf+2xxLnsXZEZWLpzuELxDpcIhbbDoIE96sjXsHDE9iQ3lA8dxtdUwZ2G4o7PRf8w",
	"zqpkCdpHZCcMnQLAGJFQ417sU4A3OAox7bnxR5uorrOtoXgBemuwZg1r7CbgjAB6eptbV7tequPlBSyf",
	"4qvNQoExKFwvqKSJBtkXnySnSk2i1EJAL6WSErh+YjqfxrwWIAMZilkOxWuaLDMpKp6a2HLKAkPwmnVO",
	"A93DZBOF3wp9zrKFPrHEW5goozSZtmMIYNhNsasM72HI8Y78OKRiJ19TzkNSi3/rMHhnbeBQ+CFb8g/O",
	"rNTDyAyM5ZOQCJkO2PC2B91AvzmKCqcGF9uTcGJOaJ7bVI6GQmHChK2AVIpQUnH2WwVkCZspccPCq0q2",
	"k0feC93Dk6OiCqbeS5YxTl06a06rXEeXc5or6KTQok/O6XGjCA6ynkteCKWRYV4i1DnB8cJ4ZTMgCnSd",
	"G5szqXRNFgGu5YasmbaeloIcEg2p5XvgaxyVDarJs+kgmopK77PA925YYMT66Z7u7sTWKSylmNGZpTkD",
	"DtKECGS2qbk229hpG6WhILNKk4RyMzpZUJ7ZsdT4sXLPfjtDONacxlFJjYoYOpfvSxutkbsb61gjSTnj",
	"S5/StVsHK5DN/n3mOHZBlaXMMMeI9jm5m/tsInBtgDJlGLRiKaQ4DXiLhySlmjbOdVHqzTl5BCqTheeb",
	"AfyZa0HmjKf4i3A7jJPPP/M9bHPUjzosNceeuz52x2H2n1DU1z3y1oZF1Hq7p01BNEgZFI307Na7ZoSJ",
	"J2aQC54Z7baHbQhyFNMcEj2L5g9hyMm4pZqdS+8AtJSU09nuYJ7EotU2DC2byMWAi0fzckG7rsO0qgpC",
	"NEvO8gpOChoBGsiZBBt5ngy0hWh3ND0pZANvILlrtt8u6hgVO85N2nrcZLvdfM5S4AncwwryMAPLhf6T",
	"8bGMrIm3VCcLzCGvMSpNWVUYWWTZ4sDk6zsHrrtiHL2z0Psf7sW6/+NbXLv/+xuW9UB8GcWT9tw2dx5F",
	"JZNWgtraL3dKD+TBI87pQY2jjwpk7+fjsHeTDfpBIN13T/053+UHWGVQB+6+3nl8JbEB06QDfOplIlQE",
	"g+ZJUq6cwZqKcBdW74AGa7e41Ecjdiyfcm7TIDNi9hfztFdBiX578X5sbSIsfOycWw/sp8Dc6kP5qD9X",
	"/FHTgbDppYrWw5HOk3OojGvm3VlN9flpGwgWp84IxRHmj4fpwU8vSI1deltaynkndlA7gJoi+ZmTF7Pq",
	"UBWnJ0cI6tgSzEeMbs2Cv1hiJ2BuEcGwI6gkjys6r4GWguMsjAn3Tf+E4z2f3oKWLFEBFVRKLHseTIRH",
	"oLfrIU0NnlN2mg3V6HDXNUhO81spreHyhvgGe0s2jyBXIG/E2qhaP9gaXPfjR77kYs0tgMMM9q2UQ+Bv",
	"pRxc4VbK9iIGbw3Fw3YVh0dWujIZsezC4EmaXYMV4xmhnDCeshVLK5oTzyCbHzgn7wT3x10BaaSBUGkg",
	"57Ci3II0cEzMjdFqKkDxfzNR6wrMl88oWnd1KvlzdOnyFUJBjL0yG1FJwrjVJUxwMpeiQDXjmHTHV8CN",
	"CbmBOeN47M6xatEqNlBV+yS7hLhVsniO9yTU5nWmysTYghPapNZiohdM2bBagq6kjUobnd8k4Xw1bSHy",
	"1LDeAzVk8CrP6SwH32R3fGq6k4UrQS4HJOMu4LQqIcHqYZ5vwjYlM5O4nKf5YmwuGPJrxMn1+7cP79/d",
	"vnsiT//zcHtJUCBxxfgwbWIGT1Eeljysj4tkCXoPqQ11brjfJYPspatIGtnukh2Ttdm9UmjgmtG8nr8R",
	"FUlElade2NPaNqoLOmM5M7J5YZmJgyknGWWNgG9h46Oj50BG2uFTWOkZiMz0hoTm+ft5dPnrnsWtMfkS",
	"H8R6A6DSkFomtXegFGtzplKYA1eucfF8C4OcYTi+h8Fi3TM7Tn6Vg1/rlEHLE6SI28p4ZGUvmPnsNPv2",
	"/H+7pjqcYLeybEdaHYUKzOVDDb1lafQ8P60H163KHtbB1OHdng7LR6ewanNFWNr0htrI+eVbKoMqby8R",
	"WCnALtA6j5rWRiuU99OyfrBAvD23HrShbuXZpGJyWrf6tIrIQXF5OM/4HEf3TS3hqF6s8PR0u5Wjqzx3",
	"50K5RHyo7xOj/lFZxeS/GQfNkpjccpDZJiZvgK42qOSvc6oUCh0X63NyS5NFnVunZAkbwhpDGRZaxusp",
	"n9M1/EV7+fsLbI3OfKG4liWCP1A9gIcvnTCXFDm6gu1XePnGisXU1onG33loR3x9EbcDCI6wzgYlBdXY",
	"crVd6HsuNVWKqf1RJS6DEe0DZTavB1QvjphnyH0CWljNP27u8qg59IhJLM+PoM2oQeP7j5+pgRZHzGIF",
	"oByM5suk1tVGNGNRGAVYugs6D8LS3hax0nEEvtKizBGCwEO3uw8Opw1Zjwcp5iyHHX0Th6c7mtakrmtt",
	"RJwpQ+u7QZ1xeGNnb4DtgNgCdqiHJUSkNb3X5RewYIh1j6CUsyI7W06+Q/+I2YwcXqqrPAD+gn3lOVX6",
	"EYBf7WzHX0um4T3PNz76D9ftgRiFxwACIV5PI1taB3EdicpTq5p+urS10lS+kLQ0oNsNAN+npo8nvEEh",
	"qN2HR2aKV6HcqTcrt64I/C7UQK+KvLus2Cm1xv365cEgfL3zO15w8e0s+/lbj7w55uLGkKC120SSXhk8",
	"6ReXd1/TcEmp7xavsKk1WebLx0zdcjrLYSD78GkBegEyyCKSMq8yvD1g5xCMCvXU7jqPgcXnF6bYLIdR",
	"+KzsnBPh4zE4rdo2uL45uIDa0Hc+KbysVx2oOrkvsQ/aTlVnVC5Faw5GnV89Irvh69uDLnrKEoQnN2dL",
	"2Ax6l6MTpA7fJjroH2jrf/4yXDm+FwnN2f8CJukKqjWkZAVSBdmwLXeWxuiCEIUdZewPdN0vYzOlWdLq",
	"GxTVLA/UOq+MF31kKXtahrodlD25OLDN/4PcV3yeAQEPCEUYmfavMQEtRkQjNSy/4JRTg4GvWaZbON/a",
	"knI3rLQ5objXREIpQWEZ0+z/DJSOSSHMv7ngGf45p0qD0kZzKlEAEahi/e1uN8de3dIVzeuHB4yuWi9A",
	"gk2ytCZgh6pxfWc5UwtIjYamK8qw8GfraraF19C0Geys2FImHL4RfpKbvTOqWDKyEhRIbK8k9NrAs/vQ",
	"PfNHXSRiyantUUZPSO4D2EceCF2BpBnUZYpa68SEzQkty5wltKVyjsi7ZLYZZA0sW2jru5yIjk8OZF91",
	"IvrELkkydAex1M3JT9i1PgNz8pRiGW/dqxxPXk1Wz2ZbORjyQIe7VfoZqFGlhXalqvNqw14fBstwQT3I",
	"dkzgrBlYlWR7XQ7trTrxGxBh9fcH9zcFFdoJUjPYr4R0QlJJpjePBnVXWQUqQV5Vtt5g//qT34P/+vQU",
	"uSeOUPvg12ZPFlqXFjBzLSidCyAcyJNkyRK78/EOYus35xJFl9FP56/OXxnOiRI4LVl0Gf2MP8VR6ZPq",
	"FxQdPXXhgvezZAHJktnUnVC6v77reiJuAqlKE7+SXGTo+5gNxlK9kWOfCLw2QPG2cPhQ1RZt0gy56D5Q",
	"ZTSKObGg9GuRbmyXMNfAbY3Pqj+z+MXflI3hmmem2ofTYX9AfOwG3vSclAZEX2W0xxoriz/YHipE4A+v",
	"Xo1CvxNyPfeeT4o+NH1DLp4mTUbGDL9wRtmxILMxdXvD/gz6qhk1fr/8g1/P8fjNjd0zYr9VIDfNK2KJ",
	"qPDiwvYXxHrqraBfWVEV0eXPr+KoYNz+8VP/BYBta5Y0g5FL+lVeHb5KO1Ny8Atp2xNk2xbCt4tCiIf0",
	"Wr+1Dx59mSi4B9VHOn3ivSJJX9rvmfGr56SRVuKuuK2AlFTpvtBffGu80ucDTsDmdyL/LyElff/C3Zf1",
	"r4CArJ1Mz7Vz7MHA06EXDX6tB1qORC8IMiYL3A+9YWCj3MMLgxiI98V9yz0FD33Y4HSK9waUOSHYRZRV",
	"XJG0kq5ZN3jvEA+Jsd4tm98+E/f4+VS2N3EPae3OAeCoIUKnWtKdOxm+CDSkdUSWGRay2qb6qvM2XfJg",
	"XYoXwxhr4QOYlvaqfkMKItuUtAfx9SXv76v3vrwkexxFAxy6tn0r7p6ta+H+j1c/T5DsApRyz8d0np00",
	"a8wlA57mGxJ88+EcYDd+PJhR09UBz4aFVw+6R8mjVUM7RH/Y6wSEKZKKtS1n+EgHRSKMcX798vwFBcy9",
	"D7Rdk3zovif0T65QHD+wkR954k6q89x3OuqPfsy/3PS/Mzf9u/jUvglnhDNdSxSOGY7/rzG2JBRfQPMB",
	"Zi/u11R6+fwR1uQkWuW4JoVd5fBD9O6DfXyje+tHEOzdcM+v2NTLHE3GvjzDTydTZo9NOmF88sFrtItv",
	"deIEg7CyGhIy11hF6FYR+4h5px8jY15RtAOhJiF0uJbYnmz64XLc653r6Td+UDHvn+8AeLYdcgQu6ijz",
	"EFt/1Qz+B5X4l7aK7Vh9j12sY+hgk/xe+ke0gl0bkghFKMmdea3n+Fsd7oUpvPnayHpP1Zn9r5ebtu8n",
	"8txezkH7B3fK+s/yHSCGtSRxQmuJzPNAnroStD9a2+3eKe/f+Wex2gJLeequKYfi3ZNbC+uxeRvvX37g",
	"Ccygpktov1km5t/VCg7I8GEOYTC8pUIvvjX9pM8H6NMtUjlCjU6UxTHZc4/slux50El7tBoLenj/ftTl",
	"ZAmr7+82p0OF78TtyVbhCLny+1/J3BXfLy8ucpHQfCGUvvzjqz++QqY239XlxQUt2Xn6B8GxD2B5nogi",
	"ev7y/H8BAAD//5P4evCWaQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
